image: golang:1.6
before_script:
  - go version
  - go get -t -v -d github.com/BytemarkHosting/bytemark-client/cmd/bytemark

test:
  script:
    - cd $GOPATH/src/github.com/BytemarkHosting/bytemark-client && make test
