before_script:
  - echo "deb http://mirror.bytemark.co.uk/debian jessie-backports main" >> /etc/apt/sources.list
  - apt-get -qq update && apt-get -qq install -y golang-go 2>&1 > /dev/null
  - apt-get -qq install -t jessie-backports -y golang-go 2>&1 > /dev/null
  - go version

go-test:
  script:
    - mkdir -p src/github.com/BytemarkHosting/bytemark-client; mv * src
    - export GOPATH=`pwd`
    - go get github.com/BytemarkHosting/auth-client
    - cd src/github.com/BytemarkHosting/bytemark-client && GO15VENDOREXPERIMENT=1 go test ./...
