image: golang:1.6

variables:
  GO15VENDOREXPERIMENT: "1"

before_script:
  # these two are needed for coverage stats
  - go get github.com/modocache/gover golang.org/x/tools/cmd/cover
  # go get the client so that we get all dependencies and test dependencies of bytemark
  - go get -t -d ./cmd/bytemark ./cmd/bytemark/util ./lib
  # then ensure that we don't have any github copy of bytemark-client lying around
  - rm -rf $GOPATH/src/github.com/BytemarkHosting/bytemark-client
  # stick our actual code in the correct place.
  - cp -r . $GOPATH/src/github.com/BytemarkHosting/bytemark-client

stages:
  - test

lint:
  stage: test
  allow_failure: true # delete me once we've got the lintiness down to 0
  script: |
    go get github.com/alecthomas/gometalinter
    gometalinter -i
    cd $GOPATH/src/github.com/BytemarkHosting/bytemark-client
    gometalinter --vendored-linters --vendor --skip=mocks --disable dupl --deadline=120s ./... | sort -t ':' -k 1,1 -k 2,2n

vet:
  stage: test
  script:
    - go vet github.com/BytemarkHosting/bytemark-client/cmd/bytemark
    - go vet github.com/BytemarkHosting/bytemark-client/cmd/bytemark/util
    - go vet github.com/BytemarkHosting/bytemark-client/lib

test:
  stage: test
  script:
    - go test -coverprofile=bytemark.coverprofile github.com/BytemarkHosting/bytemark-client/cmd/bytemark
    - go test -coverprofile=util.coverprofile github.com/BytemarkHosting/bytemark-client/cmd/bytemark/util
    - go test -coverprofile=lib.coverprofile github.com/BytemarkHosting/bytemark-client/lib
    - gover
    - go tool cover -func gover.coverprofile | tail -n 1
    - go tool cover -html gover.coverprofile -o coverage.html
  artifacts:
    paths:
    - coverage.html
