before_script:
  - echo "deb http://mirror.bytemark.co.uk/debian jessie-backports main" >> /etc/apt/sources.list
  - apt-get -qq update && apt-get -qq install -y golang-go
  - go version

go-test:
  script:
    - cd cmd/bytemark && GO15VENDOREXPERIMENT=1 go test ./...
